# -*- coding: utf-8 -*-
"""4110E001_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_XYQIpJR-9JsRTxKo3-e-8CM1FKL2zCs
"""

x = input('Enter your name:')
print('Hello, ' + x)

a = input("請輸入：")
a

a = input("請輸入：")
a
b=a+1
b

a = eval(input("請輸入："))
a

b=a+1
b

a,b = eval(input("請輸入兩個數位："))
a,b